Repository wecode-bootcamp-korea/39-1st-PickEat-backend, pull requests merged in 2022-11, with the labels that each got.

#1 초기환경세팅
  .env.sample
  .gitignore
  app.js
  db/migrations/20221115081336_create_users_table.sql
  db/migrations/20221115081403_create_user_address_table.sql
  db/migrations/20221115082099_create_product_types_table.sql
  db/migrations/20221115082100_create_categories_table.sql
  db/migrations/20221115082146_create_products_table.sql
  db/migrations/20221115082210_create_product_images_table.sql
  db/migrations/20221115082338_create_comments_table.sql
  db/migrations/20221115082340_create_order_status_table.sql
  db/migrations/20221115082350_create_order_item_status_table.sql
  db/migrations/20221115082351_create_carts_table.sql
  db/migrations/20221115082409_create_orders_table.sql
  db/migrations/20221115082417_create_order_items_table.sql
  models/dataSource.js
  package-lock.json
  package.json
  pull_request_template.md
  routes/index.js
  utils/validation.js
Labels: 완료

#2 Feature/ Get Lecture By Lecture Id api
  app.js
  controllers/lectureController.js
  db/migrations/20221115082338_create_comments_table.sql
  models/lectureDao.js
  routes/lectureRouter.js
  services/lectureService.js
  utils/checkUser.js
  utils/error.js
Labels: 완료

#4 users_API_완료
  controllers/userController.js
  models/userDao.js
  routes/index.js
  routes/userRouter.js
  services/userService.js
Labels: 완료

#8 로그인 api 구현
  controllers/userController.js
  models/userDao.js
  routes/index.js
  routes/userRouter.js
  services/userService.js
  utils/error.js
Labels: 완료

#10 signIn 코드 수정 (merge 필요)
  models/userDao.js
  utils/checkUser.js
Labels: 완료

#12 오타 수정의 건
  models/userDao.js
Labels: 완료

#14 오타 수정
  services/lectureService.js
Labels: 완료

#3 Feature/get products by query parm
  controllers/productController.js
  models/productDao.js
  routes/index.js
  routes/productRouter.js
  services/productService.js
Labels: 완료

#5 장바구니 추가 API
  controllers/cartController.js
  models/cartDao.js
  routes/cartRouter.js
  routes/index.js
  services/cartService.js
Labels: Conflict 해결 요청, 완료

#6 Feature/get cart by user
  controllers/cartController.js
  models/cartDao.js
  routes/cartRouter.js
  routes/index.js
  services/cartService.js
Labels: 완료

#15 장바구니 상품 수량 변경
  controllers/cartController.js
  models/cartDao.js
  routes/cartRouter.js
  routes/index.js
  services/cartService.js
Labels: Conflict 해결 요청, 완료

#16 오타 발견
  routes/index.js
Labels: 완료

#11 feature/commentAPI(1)
  controllers/commentController.js
  models/commentDao.js
  routes/commentRouter.js
  routes/index.js
  services/commentService.js
Labels: Conflict 해결 요청, 완료

#17 오타발견
  controllers/cartController.js
  models/cartDao.js
Labels: 멘토 리뷰 요청
